min_version = "2025.5.2"

[tools]
python = "3.11"
sops = "latest"
age = "latest"

[env]
DEV_PROJECT_ROOT = "{{ config_root }}"
_.file = [
    ".env",
    ".env.development",
    ".env.secret.json",
    ".env.development.local",
]
