min_version = "2025.5.2"

[tools]
bun = "latest"

[env]
DEV_PROJECT_ROOT = "{{ config_root }}"
DEV_CLI_DEBUG = "1"
BUN_BE_BUN = "1"
_.file = [
    ".env",
    ".env.development",
    ".env.secret.json",
    ".env.development.local",
]
