[tools]
bun = "latest"

[env]
DEV_PROJECT_ROOT = "{{ config_root }}"

[tasks.test-args]
description = "Test task that echoes all arguments"
run = "echo 'Task received arguments:' \"$@\""

[tasks.lint]
description = "Run linting"
run = "bun run lint"

[tasks.test]
description = "Run tests"
run = "bun run test"

[tasks.typecheck]
description = "Run typechecking"
run = "bun run typecheck"
