min_version = "2025.5.2"

[tools]
bun = "latest"

[env]
DEV_PROJECT_ROOT = "{{ config_root }}"
DEV_CLI_DEBUG = "1"
BUN_BE_BUN = "1"
_.file = [
    ".env",
    ".env.development",
    ".env.secret.json",
    ".env.development.local",
]

[tasks.test-args]
description = "Test task that echoes all arguments"
run = "echo 'Task received arguments:' \"$@\""

[tasks.lint]
description = "Run linting"
run = "bun run lint"

[tasks.test]
description = "Run tests"
run = "bun run test"
